# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true

- task: AzureRmWebAppDeployment@4
  inputs:
    azureSubscription: 'TheConnection'
    appType: 'webApp'
    WebAppName: 'MDPipelineTest'
    deployToSlotOrASE: true
    ResourceGroupName: 'TestPipeLines'
    SlotName: 'staging'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
